// <auto-generated />
using System;
using Blezorejemplo.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blezorejemplo.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220317071211_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("Blezorejemplo.Entidades.Productoparaayuda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductospaqueteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("descricion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductospaqueteId");

                    b.ToTable("Productoparaayuda");
                });

            modelBuilder.Entity("Blezorejemplo.Entidades.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Costo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCaducacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ganancia")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Gramo")
                        .HasColumnType("REAL");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.Property<float>("ValorInventario")
                        .HasColumnType("REAL");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Blezorejemplo.Entidades.Productosdetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Existenciaempaquetado")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Precio")
                        .HasColumnType("REAL");

                    b.Property<string>("Presentacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("cantidad")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductosDetalle");
                });

            modelBuilder.Entity("Blezorejemplo.Entidades.Productospaquete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCaducacion")
                        .HasColumnType("TEXT");

                    b.Property<float>("total")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("productospaquetes");
                });

            modelBuilder.Entity("Blezorejemplo.Entidades.Productoparaayuda", b =>
                {
                    b.HasOne("Blezorejemplo.Entidades.Productospaquete", null)
                        .WithMany("AyudaPaquete")
                        .HasForeignKey("ProductospaqueteId");
                });

            modelBuilder.Entity("Blezorejemplo.Entidades.Productosdetalle", b =>
                {
                    b.HasOne("Blezorejemplo.Entidades.Productos", null)
                        .WithMany("DetalleProducto")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Blezorejemplo.Entidades.Productos", b =>
                {
                    b.Navigation("DetalleProducto");
                });

            modelBuilder.Entity("Blezorejemplo.Entidades.Productospaquete", b =>
                {
                    b.Navigation("AyudaPaquete");
                });
#pragma warning restore 612, 618
        }
    }
}
